[workspace]
resolver = "3"
members = [
  "akari",
  "aoi",
  "ayano",
  "chiaki",
  "chikuwa",
  "ena",
  "minami",
  "nadeshiko",
  "rin",
]

[workspace.package]
edition = "2024"
license = "0BSD"
rust-version = "1.95.0"
version = "2.0.0"

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
incremental = false
lto = true
opt-level = 3
overflow-checks = true
panic = "abort"
rpath = false
strip = true
