[package]
name = "minami"
description = "Files and lists manager"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
rin = { path = "../rin" }
ena = { path = "../ena" }
chiaki = { path = "../chiaki" }
ayano = { path = "../ayano" }
chikuwa = { path = "../chikuwa" }
