[package]
name = "chiaki"
description = "Lists manager"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
chikuwa = { path = "../chikuwa" }
