[package]
name = "akari"
description = "Non-compliant HTTP(S) 1.1 client"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
chikuwa = { path = "../chikuwa" }

schannel = "0.1.22"

[dev-dependencies]
mockito = "1.1.0"
