[package]
name = "aoi"
description = "Remote control of the mpv player"
build = "rsc/build.rs"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
rin = { path = "../rin" }
chikuwa = { path = "../chikuwa" }
