[package]
name = "ayano"
description = "Non-compliant HTTP/1.1 server"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
chikuwa = { path = "../chikuwa" }
