[package]
name = "rin"
description = "Configuration files"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
chikuwa = { path = "../chikuwa" }
