[package]
name = "nadeshiko"
description = "Torrent files downloader"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
rin = { path = "../rin" }
chikuwa = { path = "../chikuwa" }
chiaki = { path = "../chiaki" }
akari = { path = "../akari" }
